image: $CI_REGISTRY_IMAGE/riscv-isa-sim:rvv

variables:
  GIT_DEPTH: 1

build:
  stage: build
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git clone --depth 1 git@github.com:sifive/bengal-team.git
    - ./configure --prefix=$(pwd)/bengal-team/spike-prefix/
    - make install -j
    - cd bengal-team
    - git submodule update --init --recursive -j `nproc` --depth 10 riscv-binutils-gdb
    - make toolchain-prefix/bin/riscv64-unknown-elf-gcc -j
    - git clone --single-branch --branch hankuanc --recurse-submodules -j `nproc` --depth 1 git@github.com:sifive/riscv-tests-internal.git
    - mkdir riscv-tests-internal/build
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - bengal-team/spike-prefix
      - bengal-team/toolchain-prefix
      - bengal-team/riscv-tests-internal

.test:
  stage: test
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - bengal-team/
    policy: pull
  script:
    - make -j
    - ctest --timeout 0.1
  after_script:
    - grep RANDOM_SEED bengal-team/riscv-tests-internal/build/CMakeCache.txt

all 0 32bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=32 -DSLEN=128 -DVLEN=512 -DXLEN=32 -DINPUT=0 ..

all 1 32bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=32 -DSLEN=128 -DVLEN=512 -DXLEN=32 -DINPUT=1 ..

random 32bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=32 -DSLEN=128 -DVLEN=512 -DXLEN=32 ..

all 0 64bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=64 -DSLEN=128 -DVLEN=512 -DXLEN=64 -DINPUT=0 ..

all 1 64bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=64 -DSLEN=128 -DVLEN=512 -DXLEN=64 -DINPUT=1 ..

random 64bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=64 -DSLEN=128 -DVLEN=512 -DXLEN=64 ..
