image: $CI_REGISTRY_IMAGE/riscv-isa-sim:rvv

variables:
  GIT_DEPTH: 1

build:
  stage: build
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git clone --depth 1 git@github.com:sifive/bengal-team.git
    - ./configure --prefix=$(pwd)/bengal-team/spike-prefix/
    - make -j `nproc` install
    - cd bengal-team
    - git submodule update --init --recursive -j `nproc` --depth 1 riscv-binutils-gdb
    - make -j `nproc` toolchain-prefix/bin/riscv64-unknown-elf-gcc
    - git clone --single-branch --branch hankuanc --recurse-submodules -j `nproc` --depth 1 git@github.com:sifive/riscv-tests-internal.git
    - mkdir riscv-tests-internal/vector/build
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - bengal-team/spike-prefix
      - bengal-team/toolchain-prefix
      - bengal-team/riscv-tests-internal

.test:
  stage: test
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - bengal-team/
    policy: pull
  script:
    - make -j `nproc`
    - ctest --timeout 0.1
  after_script:
    - grep RANDOM_SEED bengal-team/riscv-tests-internal/vector/build/CMakeCache.txt

all 0 32bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/vector/build
    - ../configure -DBASE=32 -DINPUT=0

all 1 32bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/vector/build
    - ../configure -DBASE=32 -DINPUT=1

random 32bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/vector/build
    - ../configure -DBASE=32

all 0 64bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/vector/build
    - ../configure -DBASE=64 -DINPUT=0

all 1 64bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/vector/build
    - ../configure -DBASE=64 -DINPUT=1

random 64bit:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/vector/build
    - ../configure -DBASE=64
