image: $CI_REGISTRY_IMAGE/riscv-isa-sim:rvv

variables:
  GIT_DEPTH: 1

build:
  stage: build
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git clone --depth 1 --single-branch --no-tags git@github.com:sifive/bengal-team.git
    - ./configure --prefix=$(pwd)/bengal-team/spike-prefix/
    - make install -j
    - cd bengal-team
    - git clone -b riscv-binutils-2.33.1-rvv-0.8.x --depth 1 --single-branch --no-tags --recurse-submodules -j `nproc` https://github.com/riscv/riscv-binutils-gdb.git
    - make toolchain-prefix/bin/riscv64-unknown-elf-gcc -j
    - git clone -b vector --depth 1 --single-branch --no-tags --recurse-submodules -j `nproc` git@github.com:sifive/riscv-tests-internal.git
    - git --git-dir=./riscv-tests-internal/.git rev-parse HEAD
    - mkdir riscv-tests-internal/build
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - bengal-team/spike-prefix
      - bengal-team/toolchain-prefix
      - bengal-team/riscv-tests-internal

.test:
  stage: test
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - bengal-team/
    policy: pull
  script:
    - make -j
    - ctest --timeout 0.1
  after_script:
    - grep RANDOM_SEED bengal-team/riscv-tests-internal/build/CMakeCache.txt

S128V512X32 INPUT 0:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=32 -DSLEN=128 -DVLEN=512 -DXLEN=32 -DINPUT=0 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S128V512X32 INPUT 1:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=32 -DSLEN=128 -DVLEN=512 -DXLEN=32 -DINPUT=1 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S128V512X32:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=32 -DSLEN=128 -DVLEN=512 -DXLEN=32 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S128V512X64 INPUT 0:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=64 -DSLEN=128 -DVLEN=512 -DXLEN=64 -DINPUT=0 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S128V512X64 INPUT 1:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=64 -DSLEN=128 -DVLEN=512 -DXLEN=64 -DINPUT=1 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S128V512X64:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=64 -DSLEN=128 -DVLEN=512 -DXLEN=64 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S512V512X32 INPUT 0:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=32 -DSLEN=512 -DVLEN=512 -DXLEN=32 -DINPUT=0 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S512V512X32 INPUT 1:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=32 -DSLEN=512 -DVLEN=512 -DXLEN=32 -DINPUT=1 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S512V512X32:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=32 -DSLEN=512 -DVLEN=512 -DXLEN=32 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S512V512X64 INPUT 0:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=64 -DSLEN=512 -DVLEN=512 -DXLEN=64 -DINPUT=0 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S512V512X64 INPUT 1:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=64 -DSLEN=512 -DVLEN=512 -DXLEN=64 -DINPUT=1 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..

S512V512X64:
  extends: .test
  before_script:
    - cd bengal-team/riscv-tests-internal/build
    - cmake -DRISCV_GCC=$CI_PROJECT_DIR/bengal-team/toolchain-prefix/bin/riscv64-unknown-elf-gcc -DSPIKE=$CI_PROJECT_DIR/bengal-team/spike-prefix/bin/spike -DSOFTFLOAT=$CI_PROJECT_DIR/bengal-team/spike-prefix/lib/libsoftfloat.so -DELEN=32 -DFLEN=64 -DSLEN=512 -DVLEN=512 -DXLEN=64 -DMASKING=1 -DEXCEPTION=1 -DNEGATIVE_STRIDE=1 -DNEGATIVE_INDEX=1 -DCHECK_VL=1 -DCHECK_VXSAT=1 -DCHECK_FFLAGS=1 ..
