default:
  image: docker.pkg.github.com/sifive/riscv-isa-sim/rvv:latest

variables:
  GIT_DEPTH: 1

build:
  stage: build
  script:
    - ./configure --prefix=$CI_PROJECT_DIR/riscv-isa-sim
    - make -j
    - make install -j
  artifacts:
    paths:
      - riscv-isa-sim

trigger:
  stage: .post
  trigger:
    project: root/riscv-vector-tests
    strategy: depend
    branch: master
