dist: xenial

language: python
python:
  - "3.5"

branches:
  only:
  - rvv

addons:
  apt:
    packages:
      - device-tree-compiler
      - texinfo

env:
  - BASE=32 SEED="-DSEED=\"0\""
  - BASE=32 SEED="-DSEED=\"1\""
  - BASE=32 SEED=""
  - BASE=64 SEED="-DSEED=\"0\""
  - BASE=64 SEED="-DSEED=\"1\""
  - BASE=64 SEED=""

before_install:
  - git clone git@github.com:sifive/bengal-team.git

install:
  - ./configure --prefix=$TRAVIS_BUILD_DIR/bengal-team/spike-prefix/
  - make -j $(nproc) install

before_script:
  - pip install cffi
  - cd bengal-team
  - git submodule update --init --recursive -j $(nproc) riscv-binutils-gdb
  - make -j $(nproc) toolchain-prefix/bin/riscv64-unknown-elf-gcc
  - git clone --single-branch --branch hankuanc --recurse-submodules -j $(nproc) git@github.com:sifive/riscv-tests-internal.git
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir bengal-team/riscv-tests-internal/vector/build
  - cd bengal-team/riscv-tests-internal/vector/build
  - ../configure "-DBASE=$BASE" "$SEED"
  - make -j $(nproc)
  - ctest --timeout 5
